# Generated by Django 4.1.5 on 2023-01-18 05:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contract',
            field=models.CharField(choices=[('Full-time', 'Full time'), ('Contract', 'Contract'), ('Part-time', 'Part time'), ('Temporary', 'Temporary')], max_length=20, verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.language'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='level',
            field=models.CharField(choices=[('Senior level', 'Senior'), ('Entry level', 'Entry'), ('No experience required', 'No experience required')], max_length=250, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='logo',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tool'),
        ),
    ]
