# Generated by Django 4.1.5 on 2023-01-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_listing_logo_alter_listing_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
