# Generated by Django 4.1.5 on 2023-01-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_listing_logo_alter_listing_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='logo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
