# Generated by Django 4.1.5 on 2023-01-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_listing_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contract',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Contract', 'Contract'), ('Part time', 'Part time'), ('Temporary', 'Temporary')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='level',
            field=models.CharField(choices=[('Senior', 'Senior'), ('Entry', 'Entry'), ('No experience required', 'No experience required')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack')], default='', max_length=250),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
