# Generated by Django 4.1.5 on 2023-01-19 15:07

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_listing_contract_alter_listing_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contract',
            field=models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Contract', 'Contract'), ('Part time', 'Part time'), ('Temporary', 'Temporary')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='level',
            field=models.CharField(blank=True, choices=[('Senior', 'Senior'), ('Entry', 'Entry'), ('No experience required', 'No experience required')], default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role',
            field=models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack')], default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
    ]
