# Generated by Django 4.1.5 on 2023-01-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_listing_contract_alter_listing_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='created_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='created_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
